services:
  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "/device-manager/bin/api"]
    restart: always
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=device_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=topsecretpassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d device_manager"]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always
